### ISSUE TITLE
Repo's documentation seems divorced from current AWS hosted docs

### ISSUE THREAD

**Issue by frosforever** [awsdocs/amazon-mwaa-user-guide#33]
For example https://docs.aws.amazon.com/mwaa/latest/userguide/airflow-versions.html#w305aac37c15 (accessed 2023-01-10) looks like:
<img width="818" alt="image" src="https://user-images.githubusercontent.com/1630422/211584516-ed724648-d0a5-4e93-9411-12b5cc05da6b.png">
yet current code is missing `Deferrable operators` https://github.com/awsdocs/amazon-mwaa-user-guide/blob/35187643782967056c45b1f42abde3b881faef4a/doc_source/airflow-versions.md#whats-supported-for-apache-airflow-v202

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
