### ISSUE TITLE
Smart Sensor Depreciation - 404 error response

### ISSUE THREAD

**Issue by James-Rocker** [awsdocs/amazon-mwaa-user-guide#36]
as of Airflow 2.2.4, smart sensors have been depreciated. With the service officially removed as of Airflow 2.4.0. However, the docs in [best-practices-tuning](https://github.com/awsdocs/amazon-mwaa-user-guide/blob/main/doc_source/best-practices-tuning.md) don't mention this or the alternative solution of deferrable operators.

Currently the link on [line 188](https://github.com/awsdocs/amazon-mwaa-user-guide/blob/35187643782967056c45b1f42abde3b881faef4a/doc_source/best-practices-tuning.md?plain=1#L188) in the previously referred documents just leads to nowhere resulting in a 404 response.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
